# Generated by Django 6.0.2 on 2026-02-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_business'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='businesses',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.business'),
        ),
    ]
