# Generated by Django 6.0.2 on 2026-02-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('CASH', 'Efectivo'), ('WALLET', 'Billetera'), ('BANK', 'Banco')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('SALE_INCOME', 'Ingreso por venta'), ('PURCHASE_OUTFLOW', 'Salida por compra'), ('EXPENSE', 'Gasto'), ('LOAN_IN', 'Préstamo recibido'), ('LOAN_PAYMENT', 'Pago préstamo'), ('CAPITAL_IN', 'Ingreso capital'), ('TRANSFER', 'Transferencia'), ('ADJUSTMENT', 'Ajuste')], max_length=30)),
                ('category', models.CharField(choices=[('MERCANCIA', 'Mercancía'), ('MONTAJE', 'Montaje/Mobiliario'), ('GASTOS', 'Gastos'), ('CAPITAL', 'Capital'), ('PRESTAMO', 'Préstamo'), ('TRANSFERENCIA', 'Transferencia'), ('AJUSTE', 'Ajuste'), ('VENTA', 'Venta')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
