# Generated by Django 6.0.2 on 2026-02-19 20:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('ml', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fragrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('essence_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='AlcoholCostByPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcohol_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('presentation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perfume.presentation')),
            ],
        ),
        migrations.CreateModel(
            name='PresentationDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams_essence', models.DecimalField(decimal_places=3, max_digits=10)),
                ('extras_cost', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=14)),
                ('presentation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perfume.presentation')),
            ],
        ),
    ]
