# Generated by Django 6.0.2 on 2026-02-19 20:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('product_type', models.CharField(choices=[('ESSENCE', 'Esencia'), ('RESALE', 'Producto reventa'), ('SUPPLY', 'Insumo'), ('BOTTLE', 'Envase'), ('COST_ONLY', 'Solo costo (sin stock)')], max_length=20)),
                ('unit', models.CharField(choices=[('g', 'Gramos'), ('ml', 'Mililitros'), ('unit', 'Unidad')], max_length=10)),
                ('manages_stock', models.BooleanField(default=True)),
                ('stock_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('avg_cost_per_unit', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier_name', models.CharField(blank=True, max_length=120)),
                ('invoice_number', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('MERCANCIA', 'Mercancía'), ('MONTAJE', 'Montaje/Mobiliario'), ('GASTOS', 'Gastos'), ('CAPITAL', 'Capital'), ('PRESTAMO', 'Préstamo'), ('TRANSFERENCIA', 'Transferencia'), ('AJUSTE', 'Ajuste'), ('VENTA', 'Venta')], default='MERCANCIA', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('ledger_created', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paid_from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
    ]
