# Generated by Django 6.0.2 on 2026-02-19 20:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('PERFUME', 'Perfume preparado'), ('PRODUCT', 'Producto normal'), ('ESSENCE', 'Esencia por gramos')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=14)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
        ),
    ]
