# Generated by Django 6.0.2 on 2026-02-19 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('perfume', '0001_initial'),
        ('sales', '0003_sale_total_cost_sale_total_profit_saleitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at'], 'permissions': [('can_refund', 'Can refund/void sales')]},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='saleitem',
            name='fragrance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perfume.fragrance'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='grams_used',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perfume.presentation'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
    ]
